In [ ]:
import numpy as np
# Creating arrays
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
zerosa=np.zeros((3,3),dtype=int)
print(zerosa)
onesa=np.zeros((2,2),dtype=int)
print(onesa)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0]
 [0 0]]


In [ ]:
zerosa=np.zeros((3,3),dtype=float)
print(zerosa)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
# Creating arrays
arr= np.array([1,2,3,4,5])
print(arr)
#Array manipulation
reshapedarr=arr.reshape(5,1)
print(reshapedarr)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
import numpy as np
# Creating arrays
arr= np.array([1,2,3,4,5])
print(arr)
#Array manipulation
reshapedarr=arr.reshape(5,1)
print(reshapedarr)
slicedarr=arr[2:4]
print(slicedarr)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
b=np.split(a,4)
print(b)

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data=np.loadtxt("/DAP.txt",dtype=int)
d=np.savetxt("/data.txt",data)
print(d)
print(data)

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


<ipython-input-27-3bac3d5b8e92>:1: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  data=np.loadtxt("/DAP.txt",dtype=int)
